# Generated by Django 4.2.8 on 2023-12-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
